name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment:
      name: AzurePAT
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./commit.sh
         ./commit.sh
      shell: bash
