name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{env.AzurePAT.AZUREPAT}}
        AZUSERNAME: "ek";
      run: |
         chmod +x ./commit.sh
         ./commit.sh
      shell: bash
